export const symptoms = {
    longBreath: "verlängerte Ausatmung",
    whistlingBreath: "pfeifende Atmung",
    dyspnoe: "Dyspnoe",
    cough: "Husten 🤧",
    fear: "Angst 😨",
    rattleSound: "Rasselgeräusche 🪇",
    unilateralChestPain: "einseitiger Brustschmerz",
    strongChestPain: "starke Brustschmerz",
    bloodyBody: "Blutung am Bauch 🩸",
    swellling: "Schwellung",
    skinRash: "Hautausschlag",
    nausea: "Übelkeit 🤢",
    vertigo: "Schwindel 🫨",
    fatigue: "Müdigkeit 😴",
    itching: "Jucken",
    balanceDisorder: "Gleichgewichtsstörung",
    sweat: "Schwitzen 🥵",
    breathProblems: "Atemprobleme",
    diffrentBreath: "veränderte Atmung",
    vomiting: "Erbrechen 🤮",
    consciousnessDisorder: "Bewusstseinsstörung",
    pupilDisorder: "Pupillenstörung",
    speechDisorder: "Sprachstörung",
    unilateralParalysis: "einseitige Lähmung",
    trembling: "Zittern",
    stiffening: "Versteifung",
    urineCollection: "Urinabgabe",
    stomachAche: "Bauchschmerzen",
    hyperactivity: "Hyperaktivität",
    sweetBreath: "süßlicher Atemgeruch",
    thirst: "Durst",
    cold: "Kälte 🥶",
    confusion: "Verwirrtheit",
    drySkin: "trockene Haut",
    headache: "Kopfschmerzen",
    neckPain: "Nackenschmerzen",
    freezing: "Frieren 🥶",
    redness: "Rötung",
    blisters: "Blasen",
    abnormalPosition: "abnormale Lage",
    abnormalMobility: "abnormale Beweglichkeit",
    visibleBoneEnds: "zusehende Knochenenden 🦴",
    minorBleeding: "geringe Blutung 🩸",
    minorInjuries: "leichte Verletzungen",
    memoryLapses: "Erinnerungslücken",
    bleedingNoseEarMouth: "Blutung Nase/Ohr/Mund 🩸",
    cramps: "Krämpfe",
    leakageBrainMatter: "Austreten von Hirnmasse",
    paralysis: "Lähmung",
    numbness: "Taubheitsgefühl",
    panic: "Panik",
    heavyBleeding: "starke Blutung 🩸",
    severePain: "starke Schmerzen",
    motionlessState: "bewegungslose Lage",
}

export const skinColor = {
    zyanotisch: "zyanotisch",
    pale: "blass",
    normal: "normal",
    paleBlue: "blass-blau",
    blueRed: "blau-rot",
    red: "rot",
    diffrent: "verändert",

}