export const causes = {
    anaphylaxis: "Anaphylaxie",
    asthma: "Asthma",
    barotrauma: "Barotrauma",
    coPoisoning: "CO-Vergiftung",
    decompressionSickness: "Dekompression",
    frostbite: "Erfrierung",
    fracture: "Fraktur",
    heartAttack: "Herzinfarkt",
    heatExhaustion: "Hitzeerschöpfung",
    heatstroke: "Hitzeschlag",
    hyperglycemia: "Hyperglykämie",
    hyperventilation: "Hyperventilation",
    hypoglycemia: "Hypoglykämie",
    internalBleeding: "Innere Blutung",
    intoxication: "Intoxikation",
    seizure: "Krampfanfall",
    pulmonaryEdema: "Lungenödem",
    pneumothorax: "Pneumothorax",
    backInjury: "Rückenverletzung",
    headInjury: "Schädelhirntrauma",
    skullFracture: "Schädelbruch",
    stroke: "Schlaganfall",
    sunStroke: "Sonnenstich",
    bleeding: "starke Blutung",
    hypothermia: "Unterkühlung",
    burn: "Verbrennung",
    airwayObstruction: "Verlegung der Atemwege",
    poisoning: "Vergiftung",
    wounds: "Wunden",
};


export const causesArray = Object.values(causes)