export const causes = {
    asthma: "Asthma",
    airwayObstruction: "Verlegung der Atemwege",
    pulmonaryEdema: "Lungenödem",
    pneumothorax: "Pneumothorax",
    anaphylaxis: "Anaphylaxie",
    //drowning: "Ertrinken",
    decompressionSickness: "Dekompression",
    coPoisoning: "CO-Vergiftung",
    heartAttack: "Herzinfarkt",
    intoxication: "Intoxikation",
    poisoning: "Vergiftung",
    stroke: "Schlaganfall",
    seizure: "Krampfanfall",
    internalBleeding: "Innere Blutung",
    hypoglycemia: "Hypoglykämie",
    hyperglycemia: "Hyperglykämie",
    frostbite: "Erfrierung",
    hypothermia: "Unterkühlung",
    heatstroke: "Hitzeschlag",
    sunStroke: "Sonnenstich",
    heatExhaustion : "Hitzeerschöpfung",
    burn: "Verbrennung",
    fracture: "Fraktur",
    wounds: "Wunden",
    headInjury: "Schädelhirntrauma",
    skullFracture: "Schädelbruch",
    barotrauma: "Barotrauma",
    hyperventilation: "Hyperventilation",
};

export const causesArray = Object.values(causes)