export const measure = {
    AED : "AED",
    calmDown : "Beruhigen",
    activity : "Bewegung",
    pressureBandage : "Druckverband",
    flatStorage : "flache Lagerung",
    leaveDangerZone : "Gefahrenzone verlassen",
    HLW : "HLW",
    elevatedPosition : "Hochlagerung",
    HWS : "HWS",
    bag: "Hyperventilationsbeutel",
    sterileCover : "keimfrei bedecken",
    freeze: "kühlen",
    stopBleeding : "leichte Blutung stillen",
    medication : "Medikation",
    food: "Nahrung",
    emergencyCall : "Notruf",
    oxygen : "Sauerstoff",
    lateralPosition : "Seitenlage",
    shockPosition : "Schocklage",
    spineboard : "Spineboard",
    glucose : "Traubenzucker",
    drink : "Trinken",
    measureTime : "Zeit messen",
}