//eigensicherung"
//random bewusstlos werden anch 2min
export const measure = {
    AED : "AED",
    calmDown : "Beruhigen",
    activity : "Bewegung",
    pressureBandage : "Druckverband",
    selfProtection: "Eigensicherung",
    flatStorage : "flache Lagerung",
    secretManeuver: "Heimlichmanöver",
    HLW : "HLW",
    elevatedPosition : "Oberkörper hochlagern",
    HWS : "HWS",
    bag: "Hyperventilationsbeutel",
    sterileCover : "keimfrei bedecken",
    compression : "Kompression",
    freeze: "kühlen",
    frozenPlace : "kühler Ort/Schatten",
    stopBleeding : "leichte Blutung stillen",
    medication : "Medikation",
    food: "Nahrung",
    emergencyCall : "Notruf",
    lunch : "Pause",
    oxygen : "Sauerstoff 4L",
    moreOxygen : "Sauerstoff 15L",
    lateralPosition : "Seitenlage",
    smallShockPosition: "teilweise Schocklage (bei Kontraindikation)",
    shockPosition : "Schocklage",
    spineboard : "Spineboard",
    glucose : "Traubenzucker",
    drink : "Trinken",
    warmth : "Wärme",
    measureTime : "Zeit messen",
}